#gt915 touchpanel driver


obj-$(CONFIG_GT9XX_TOUCHPANEL_QC_DRIVER)	+= gt9xx.o
#gt915 update file
obj-$(CONFIG_GT9XX_TOUCHPANEL_QC_UPDATE)	+= gt9xx_update.o
#debug tool
obj-$(CONFIG_GT9XX_TOUCHPANEL_QC_DEBUG)		+= goodix_tool.o
